#!/bin/bash

cat << EndOfMessage 
read -p "Create new script? " -n 1 -r 
echo    # (optional) move to a new line 
if [[ $REPLY =~ ^[Yy]$ ]] 
then 
  echo "#!/bin/bash" > ~/scripts/unclassified/$1 
  vim ~/scripts/unclassified/$1 
fi 
